# This file was generated by the {rix} R package v0.18.1 on 2026-01-30
# with following call:
# >rix(date = "2025-09-09",
#  > r_pkgs = c("languageserver",
#  > "pacman",
#  > "rix",
#  > "here",
#  > "data.table",
#  > "dplyr",
#  > "ggplot2",
#  > "sf",
#  > "comtradr",
#  > "countrycode",
#  > "did2s",
#  > "fixest",
#  > "texreg",
#  > "broom",
#  > "haven",
#  > "fs",
#  > "stringr",
#  > "glue",
#  > "purrr",
#  > "tidyr",
#  > "readr",
#  > "readxl",
#  > "zoo",
#  > "kableExtra",
#  > "bit64",
#  > "tidyfast",
#  > "tradestatistics",
#  > "rmapshaper"),
#  > system_pkgs = NULL,
#  > git_pkgs = list(list(package_name = "concordance",
#  > repo_url = "https://github.com/insongkim/concordance",
#  > commit = "de8517e0fa2b6cd0de8c02bcb7ba4583cde76aa7"),
#  >      list(package_name = "ssaggregate",
#  > repo_url = "https://github.com/kylebutts/ssaggregate",
#  > commit = "22df93980250891a0cc247f6020136cd33c65ba2")),
#  > ide = "none",
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = TRUE,
#  > r_ver = "4.5.1")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-09-09.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      bit64
      broom
      comtradr
      countrycode
      data_table
      did2s
      dplyr
      fixest
      fs
      ggplot2
      glue
      haven
      here
      kableExtra
      languageserver
      pacman
      purrr
      readr
      readxl
      rix
      rmapshaper
      sf
      stringr
      texreg
      tidyfast
      tidyr
      tradestatistics
      zoo;
  };
 
    concordance = (pkgs.rPackages.buildRPackage {
      name = "concordance";
      src = pkgs.fetchgit {
        url = "https://github.com/insongkim/concordance";
        rev = "de8517e0fa2b6cd0de8c02bcb7ba4583cde76aa7";
        sha256 = "sha256-kciV7nnfvi78hyHRl2pt3gihLJj4r/sh74+et+JNCpE=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          dplyr
          purrr
          rlang
          stringr
          tibble
          tidyr;
      };
    });

    ssaggregate = (pkgs.rPackages.buildRPackage {
      name = "ssaggregate";
      src = pkgs.fetchgit {
        url = "https://github.com/kylebutts/ssaggregate";
        rev = "22df93980250891a0cc247f6020136cd33c65ba2";
        sha256 = "sha256-ZR88Xl0kuXpB2Xf06l691pKTYFle8fKE+DlXryM0MR8=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          data_table
          fixest
          haven;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ concordance ssaggregate rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
